---
sidebar: sidebar 
permalink: rn/whats_new.html 
keywords:  
summary:  
---
= Novedades de la API ASTRA Control REST
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp actualiza periódicamente la API REST de Astra Control para ofrecerle nuevas funciones, mejoras y correcciones de errores.



== 5 de agosto de 2021 (21.08)

Esta versión incluye la introducción de un nuevo modelo de puesta en marcha de Astra y una importante ampliación de LA API DE REST.



=== Modelo de implementación de Astra Control Center

Además de la oferta existente de Astra Control Service que se proporciona como servicio de cloud público, esta versión incluye también el modelo de puesta en marcha en las instalaciones de Astra Control Center. Puede instalar Astra Control Center en sus instalaciones para gestionar su entorno local de Kubernetes. Los dos modelos de puesta en marcha de Astra Control comparten la misma API DE REST, con pequeñas diferencias observadas en la documentación.



=== Expansión de los tipos de recursos de REST

El número de recursos a los que se puede acceder mediante la API REST de Astra Control se ha ampliado enormemente y muchos de los nuevos recursos proporcionan una base para la oferta local de Astra Control Center. Los nuevos recursos incluyen: ASUP, autorización, función, licencia, configuración suscripción, bloque, cloud, clúster, clúster gestionado, storage backend y clase de almacenamiento. Consulte link:../endpoints/resources.html["Recursos"] si quiere más información.



=== Puntos finales adicionales compatibles con la implementación de Astra

Además de los recursos REST ampliados, hay varios otros extremos API nuevos disponibles para admitir una puesta en marcha de Astra Control.

Soporte para openapi:: Los extremos de OpenAPI proporcionan acceso al documento JSON de OpenAPI actual y a otros recursos relacionados.
Compatibilidad con OpenMetrics:: Los extremos de OpenMetrics proporcionan acceso a las métricas de cuentas mediante el recurso OpenMetrics.




== 15 de abril de 2021 (21.04)

Esta versión incluye las siguientes funciones y mejoras nuevas.



=== Introducción de la API de REST

La API REST de Astra Control está disponible para su uso con la oferta de Astra Control Service. Se ha creado a partir de tecnologías DE REST y prácticas recomendadas vigentes. La API proporciona una base para la automatización de sus implementaciones de Astra e incluye las siguientes funciones y ventajas.

Recursos:: Hay catorce tipos de recursos DE REST disponibles.
Acceso de token de API:: El acceso a la API DE REST se proporciona mediante un token de acceso de la API que se puede generar en la interfaz de usuario web de Astra. El token de API proporciona acceso seguro a la API.
Soporte para colecciones:: Hay un amplio conjunto de parámetros de consulta que se pueden utilizar para tener acceso a las colecciones de recursos. Algunas de las operaciones admitidas son el filtrado, la ordenación y la paginación.

