---
sidebar: sidebar 
permalink: workflows/wf_list_unman_apps.html 
keywords:  
summary:  
---
= Enumere las aplicaciones no administradas
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Puede enumerar las aplicaciones que actualmente no están gestionadas por Astra. Puede hacerlo como parte de la selección de una aplicación que se va a gestionar.


NOTE: Este flujo de trabajo enumera todas las aplicaciones Astra. Puede examinar el resultado para determinar qué aplicaciones no se gestionan examinando `managedState` campo.



=== 1. Enumere las aplicaciones

Realice la siguiente llamada de API de REST.

[cols="25,75"]
|===
| Método HTTP | Ruta 


| OBTENGA | /Account/{accountID}/topolog/v1/apps 
|===


===== Parámetros de entrada adicionales

Además de los parámetros comunes con todas las llamadas API DE REST, en los ejemplos curl de este paso se incluyen los siguientes parámetros.

[cols="25,10,10,55"]
|===
| Parámetro | Tipo | Obligatorio | Descripción 


| incluya | Consulta | No | Opcionalmente, seleccione los valores que desea devolver en la respuesta. 
|===


===== Ejemplo de curl: Devuelve todos los datos de todas las aplicaciones

[source, curl]
----
curl --location -i --request GET 'https://astra.netapp.io/accounts/<ACCOUNT_ID>/topology/v1/apps' --header 'Accept: */*' --header 'Authorization: Bearer <API_TOKEN>'
----


===== Ejemplo de curl: Devuelve el nombre, id y managedState para todas las aplicaciones

[source, curl]
----
curl --location -i --request GET 'https://astra.netapp.io/accounts/<ACCOUNT_ID>/topology/v1/apps?include=name,id,managedState' --header 'Accept: */*' --header 'Authorization: Bearer <API_TOKEN>'
----


===== Ejemplo de resultado JSON

[source, json]
----
{
  "items": [
    [
      "maria",
      "eed19f78-0884-4792-bb7a-313258c6b0b1",
      "unmanaged"
    ],
    [
      "mariadb-mariadb",
      "8da20fff-c69c-4170-bb0d-e4f91c5a1333",
      "managed"
    ],
    [
      "test-postgres-app",
      "1ee6235b-cda1-45cb-8d4c-630bdb8b41a5",
      "unmanaged"
    ],
    [
      "postgres1-postgresql",
      "e591ee59-ea90-4a9f-8e6c-d2b6e8647096",
      "unmanaged"
    ],
    [
      "kube-system",
      "077a2f73-4b51-4d04-8c6c-f63b3b069755",
      "unmanaged"
    ],
    [
      "trident",
      "5b6fc28f-e308-4653-b9d2-6d66a764d2e1",
      "unmanaged"
    ],
    [
      "postgres1-postgresql-clone",
      "06be05c5-763e-4d73-bd06-1f27f5f2e130",
      "unmanaged"
    ],
    [
      "davidns-postgres-app",
      "11e046b7-ec64-4184-85b3-debcc3b1da4d",
      "managed"
    ]
  ],
  "metadata": {}
}
----