---
sidebar: sidebar 
permalink: information/additional_resources.html 
keywords:  
summary:  
---
= Recursos adicionales
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Hay recursos adicionales a los que puede acceder para obtener ayuda y obtener más información sobre los servicios cloud de NetApp y la compatibilidad, así como sobre conceptos generales DE REST y cloud.



== Astra

* https://["Documentación de Astra Control Center 2108"^]
+
La documentación para el software Astra Control Center implementada en las instalaciones del cliente.

* https://["Documentación de Astra Control Service"^]
+
Documentación sobre el software Astra Control Service disponible en la nube pública.

* https://["Documentación de Astra Trident"^]
+
Documentación para el orquestador de almacenamiento de código abierto Astra Trident mantenido por NetApp.





== Recursos de cloud de NetApp

* https://["Soluciones cloud de NetApp"^]
+
Sitio central de las soluciones cloud de NetApp.

* https://["Consola Cloud Central de NetApp"^]
+
Consola de servicio Cloud Central de NetApp con inicio de sesión.

* https://["Soporte de NetApp"^]
+
Acceda a herramientas de solución de problemas, documentación y asistencia de soporte técnico.





== Conceptos DE REST y tecnología cloud

* Doctorado https://["disertación"^] Por Roy Fiding
+
En esta publicación se introdujo y se estableció el modelo de desarrollo de aplicaciones DE REST.

* https://["Auth0"^]
+
Se trata del servicio de plataforma de autenticación y autorización utilizado por el servicio Astra para el acceso a la Web.

* https://["Editor RFC"^]
+
Fuente autoritativa para estándares web e Internet que se mantiene como una colección de documentos RFC con números únicos.


